import mongoose from "mongoose";
import { env } from "../config/env";
import { Role } from "../models/Role";

const roles = [
  {
    title: "Frontend Developer",
    slug: "frontend-developer",
    description: "Builds user-facing web interfaces using modern frameworks, focusing on performance, accessibility, and responsive design.",
    demandLevel: "high" as const,
    averageSalary: "$70,000 - $130,000",
    requiredSkills: [
      { name: "HTML", priority: "essential" as const, category: "Core" },
      { name: "CSS", priority: "essential" as const, category: "Core" },
      { name: "JavaScript", priority: "essential" as const, category: "Core" },
      { name: "TypeScript", priority: "important" as const, category: "Core" },
      { name: "React", priority: "essential" as const, category: "Framework" },
      { name: "Next.js", priority: "important" as const, category: "Framework" },
      { name: "TailwindCSS", priority: "important" as const, category: "Styling" },
      { name: "Redux", priority: "nice-to-have" as const, category: "State Management" },
      { name: "Git", priority: "essential" as const, category: "Tools" },
      { name: "Webpack", priority: "nice-to-have" as const, category: "Tools" },
      { name: "Vite", priority: "nice-to-have" as const, category: "Tools" },
      { name: "Jest", priority: "important" as const, category: "Testing" },
      { name: "Cypress", priority: "nice-to-have" as const, category: "Testing" },
      { name: "REST API", priority: "essential" as const, category: "Backend Integration" },
      { name: "GraphQL", priority: "nice-to-have" as const, category: "Backend Integration" },
      { name: "Figma", priority: "nice-to-have" as const, category: "Design" },
      { name: "Responsive Design", priority: "essential" as const, category: "Core" },
      { name: "Web Accessibility", priority: "important" as const, category: "Core" },
    ],
  },
  {
    title: "Backend Developer",
    slug: "backend-developer",
    description: "Designs and implements server-side logic, APIs, databases, and system architecture for scalable applications.",
    demandLevel: "high" as const,
    averageSalary: "$80,000 - $140,000",
    requiredSkills: [
      { name: "Node.js", priority: "essential" as const, category: "Runtime" },
      { name: "TypeScript", priority: "important" as const, category: "Language" },
      { name: "Express", priority: "essential" as const, category: "Framework" },
      { name: "Python", priority: "nice-to-have" as const, category: "Language" },
      { name: "PostgreSQL", priority: "essential" as const, category: "Database" },
      { name: "MongoDB", priority: "important" as const, category: "Database" },
      { name: "Redis", priority: "important" as const, category: "Database" },
      { name: "REST API", priority: "essential" as const, category: "API" },
      { name: "GraphQL", priority: "nice-to-have" as const, category: "API" },
      { name: "Docker", priority: "important" as const, category: "DevOps" },
      { name: "Git", priority: "essential" as const, category: "Tools" },
      { name: "JWT", priority: "essential" as const, category: "Security" },
      { name: "OAuth", priority: "nice-to-have" as const, category: "Security" },
      { name: "SQL", priority: "essential" as const, category: "Database" },
      { name: "Microservices", priority: "nice-to-have" as const, category: "Architecture" },
      { name: "CI/CD", priority: "important" as const, category: "DevOps" },
      { name: "Linux", priority: "important" as const, category: "Infrastructure" },
    ],
  },
  {
    title: "Full Stack Developer",
    slug: "full-stack-developer",
    description: "Works across the entire web stack — from frontend UI to backend APIs and databases — delivering complete features end-to-end.",
    demandLevel: "high" as const,
    averageSalary: "$85,000 - $150,000",
    requiredSkills: [
      { name: "HTML", priority: "essential" as const, category: "Frontend" },
      { name: "CSS", priority: "essential" as const, category: "Frontend" },
      { name: "JavaScript", priority: "essential" as const, category: "Core" },
      { name: "TypeScript", priority: "important" as const, category: "Core" },
      { name: "React", priority: "essential" as const, category: "Frontend" },
      { name: "Next.js", priority: "important" as const, category: "Frontend" },
      { name: "Node.js", priority: "essential" as const, category: "Backend" },
      { name: "Express", priority: "essential" as const, category: "Backend" },
      { name: "MongoDB", priority: "important" as const, category: "Database" },
      { name: "PostgreSQL", priority: "important" as const, category: "Database" },
      { name: "REST API", priority: "essential" as const, category: "API" },
      { name: "Git", priority: "essential" as const, category: "Tools" },
      { name: "Docker", priority: "important" as const, category: "DevOps" },
      { name: "TailwindCSS", priority: "nice-to-have" as const, category: "Frontend" },
      { name: "Redis", priority: "nice-to-have" as const, category: "Database" },
      { name: "AWS", priority: "nice-to-have" as const, category: "Cloud" },
      { name: "CI/CD", priority: "nice-to-have" as const, category: "DevOps" },
      { name: "JWT", priority: "essential" as const, category: "Security" },
    ],
  },
  {
    title: "DevOps Engineer",
    slug: "devops-engineer",
    description: "Bridges development and operations by automating infrastructure, CI/CD pipelines, monitoring, and cloud deployments.",
    demandLevel: "high" as const,
    averageSalary: "$90,000 - $160,000",
    requiredSkills: [
      { name: "Linux", priority: "essential" as const, category: "Infrastructure" },
      { name: "Docker", priority: "essential" as const, category: "Containerization" },
      { name: "Kubernetes", priority: "essential" as const, category: "Orchestration" },
      { name: "AWS", priority: "essential" as const, category: "Cloud" },
      { name: "Terraform", priority: "important" as const, category: "IaC" },
      { name: "Ansible", priority: "nice-to-have" as const, category: "IaC" },
      { name: "CI/CD", priority: "essential" as const, category: "Automation" },
      { name: "Jenkins", priority: "important" as const, category: "Automation" },
      { name: "Git", priority: "essential" as const, category: "Tools" },
      { name: "Python", priority: "important" as const, category: "Scripting" },
      { name: "Bash", priority: "essential" as const, category: "Scripting" },
      { name: "Nginx", priority: "important" as const, category: "Infrastructure" },
      { name: "Monitoring", priority: "important" as const, category: "Observability" },
      { name: "PostgreSQL", priority: "nice-to-have" as const, category: "Database" },
      { name: "Redis", priority: "nice-to-have" as const, category: "Database" },
      { name: "Networking", priority: "important" as const, category: "Infrastructure" },
      { name: "Security", priority: "important" as const, category: "Security" },
    ],
  },
  {
    title: "Mobile App Developer",
    slug: "mobile-app-developer",
    description: "Specializes in building native or cross-platform applications for iOS and Android, focusing on mobile performance and touch-based UX.",
    demandLevel: "high" as const,
    averageSalary: "$85,000 - $145,000",
    requiredSkills: [
      { name: "React Native", priority: "essential" as const, category: "Framework" },
      { name: "Flutter", priority: "important" as const, category: "Framework" },
      { name: "Swift", priority: "important" as const, category: "Language" },
      { name: "Kotlin", priority: "important" as const, category: "Language" },
      { name: "Mobile UI/UX", priority: "essential" as const, category: "Design" },
      { name: "Firebase", priority: "essential" as const, category: "Backend" },
      { name: "App Store Deployment", priority: "important" as const, category: "Tools" },
      { name: "SQLite", priority: "important" as const, category: "Database" },
    ],
  },
  {
    title: "Data Engineer",
    slug: "data-engineer",
    description: "Constructs and maintains the 'pipes' that connect data sources to data sinks, ensuring data quality and efficient ETL processes.",
    demandLevel: "high" as const,
    averageSalary: "$95,000 - $165,000",
    requiredSkills: [
      { name: "Python", priority: "essential" as const, category: "Language" },
      { name: "SQL", priority: "essential" as const, category: "Language" },
      { name: "Apache Spark", priority: "essential" as const, category: "Big Data" },
      { name: "Kafka", priority: "important" as const, category: "Streaming" },
      { name: "Airflow", priority: "important" as const, category: "Orchestration" },
      { name: "Snowflake", priority: "important" as const, category: "Warehouse" },
      { name: "ETL Design", priority: "essential" as const, category: "Core" },
    ],
  },
  {
    title: "Security Engineer",
    slug: "security-engineer",
    description: "Protects systems and data by identifying vulnerabilities, implementing defenses, and responding to security incidents.",
    demandLevel: "high" as const,
    averageSalary: "$100,000 - $175,000",
    requiredSkills: [
      { name: "Penetration Testing", priority: "important" as const, category: "Testing" },
      { name: "Cryptography", priority: "essential" as const, category: "Core" },
      { name: "Network Security", priority: "essential" as const, category: "Infrastructure" },
      { name: "IAM", priority: "important" as const, category: "Security" },
      { name: "SIEM", priority: "important" as const, category: "Tools" },
      { name: "Cloud Security", priority: "essential" as const, category: "Cloud" },
      { name: "OWASP", priority: "essential" as const, category: "Standards" },
    ],
  },
  {
    title: "Machine Learning Engineer",
    slug: "machine-learning-engineer",
    description: "Researches, builds, and designs self-running software to automate predictive models and AI-driven features.",
    demandLevel: "high" as const,
    averageSalary: "$110,000 - $190,000",
    requiredSkills: [
      { name: "Python", priority: "essential" as const, category: "Language" },
      { name: "PyTorch", priority: "essential" as const, category: "Framework" },
      { name: "TensorFlow", priority: "important" as const, category: "Framework" },
      { name: "Scikit-learn", priority: "essential" as const, category: "Library" },
      { name: "Math & Statistics", priority: "essential" as const, category: "Core" },
      { name: "MLOps", priority: "important" as const, category: "DevOps" },
      { name: "Pandas", priority: "essential" as const, category: "Data Science" },
    ],
  },
  {
    title: "QA Automation Engineer",
    slug: "qa-automation-engineer",
    description: "Develops automated scripts and frameworks to test software quality, performance, and reliability throughout the SDLC.",
    demandLevel: "medium" as const,
    averageSalary: "$75,000 - $135,000",
    requiredSkills: [
      { name: "Selenium", priority: "essential" as const, category: "Tools" },
      { name: "Playwright", priority: "important" as const, category: "Tools" },
      { name: "Python", priority: "important" as const, category: "Scripting" },
      { name: "Cypress", priority: "important" as const, category: "Tools" },
      { name: "API Testing", priority: "essential" as const, category: "Core" },
      { name: "JUnit", priority: "nice-to-have" as const, category: "Testing" },
      { name: "CI/CD", priority: "important" as const, category: "DevOps" },
    ],
  },
  {
    title: "Site Reliability Engineer (SRE)",
    slug: "sre",
    description: "Applies software engineering mindsets to system administration, focusing on system uptime, latency, and operational efficiency.",
    demandLevel: "high" as const,
    averageSalary: "$100,000 - $170,000",
    requiredSkills: [
      { name: "Go", priority: "important" as const, category: "Language" },
      { name: "Kubernetes", priority: "essential" as const, category: "Orchestration" },
      { name: "Prometheus", priority: "essential" as const, category: "Monitoring" },
      { name: "Grafana", priority: "essential" as const, category: "Observability" },
      { name: "Incident Management", priority: "essential" as const, category: "Process" },
      { name: "Terraform", priority: "important" as const, category: "IaC" },
      { name: "SLIs/SLOs", priority: "essential" as const, category: "Core" },
    ],
  },
  {
    title: "Cloud Architect",
    slug: "cloud-architect",
    description: "Designs the overall cloud infrastructure strategy, ensuring scalability, cost-efficiency, and resilience across providers.",
    demandLevel: "high" as const,
    averageSalary: "$120,000 - $200,000",
    requiredSkills: [
      { name: "AWS", priority: "essential" as const, category: "Cloud" },
      { name: "Azure", priority: "important" as const, category: "Cloud" },
      { name: "Cloud Design Patterns", priority: "essential" as const, category: "Architecture" },
      { name: "Cost Optimization", priority: "important" as const, category: "Strategy" },
      { name: "Networking", priority: "essential" as const, category: "Infrastructure" },
      { name: "Serverless", priority: "important" as const, category: "Architecture" },
    ],
  },
  {
    title: "Embedded Systems Engineer",
    slug: "embedded-systems-engineer",
    description: "Develops software for hardware devices with limited resources, focusing on real-time performance and hardware integration.",
    demandLevel: "medium" as const,
    averageSalary: "$80,000 - $150,000",
    requiredSkills: [
      { name: "C", priority: "essential" as const, category: "Language" },
      { name: "C++", priority: "essential" as const, category: "Language" },
      { name: "RTOS", priority: "important" as const, category: "Core" },
      { name: "Microcontrollers", priority: "essential" as const, category: "Hardware" },
      { name: "Linux Kernel", priority: "nice-to-have" as const, category: "Infrastructure" },
      { name: "PCB Design", priority: "nice-to-have" as const, category: "Hardware" },
    ],
  },
  {
    title: "Data Scientist",
    slug: "data-scientist",
    description: "Extracts insights from complex datasets using statistical analysis and visualization to drive business decisions.",
    demandLevel: "high" as const,
    averageSalary: "$90,000 - $160,000",
    requiredSkills: [
      { name: "Python", priority: "essential" as const, category: "Language" },
      { name: "R", priority: "nice-to-have" as const, category: "Language" },
      { name: "Tableau", priority: "important" as const, category: "Visualization" },
      { name: "SQL", priority: "essential" as const, category: "Database" },
      { name: "A/B Testing", priority: "important" as const, category: "Statistics" },
      { name: "Data Storytelling", priority: "essential" as const, category: "Communication" },
    ],
  },
  {
    title: "Blockchain Developer",
    slug: "blockchain-developer",
    description: "Designs and implements smart contracts and decentralized applications (dApps) on distributed ledger technologies.",
    demandLevel: "medium" as const,
    averageSalary: "$95,000 - $180,000",
    requiredSkills: [
      { name: "Solidity", priority: "essential" as const, category: "Language" },
      { name: "Rust", priority: "important" as const, category: "Language" },
      { name: "Ethereum", priority: "essential" as const, category: "Blockchain" },
      { name: "Web3.js", priority: "important" as const, category: "Integration" },
      { name: "Cryptography", priority: "essential" as const, category: "Core" },
      { name: "Smart Contract Auditing", priority: "important" as const, category: "Security" },
    ],
  },
];

async function seed() {
  try {
    await mongoose.connect(env.MONGODB_URI);
    console.log("Connected to MongoDB");

    await Role.deleteMany({});
    console.log("Cleared existing roles");

    await Role.insertMany(roles);
    console.log(`Seeded ${roles.length} roles successfully`);

    await mongoose.disconnect();
    console.log("Done!");
    process.exit(0);
  } catch (error) {
    console.error("Seeding error:", error);
    process.exit(1);
  }
}

seed();
